syntax = "proto3";

option java_package = "com.somewear.gen";

import "timestamp_proto.proto";
import "tracking_session_proto.proto";

enum TargetState {
    TARGET_STATE_UNKNOWN = 0;
    TARGET_STATE_ACTIVE = 1;
    TARGET_STATE_INACTIVE = 2;
    TARGET_STATE_ACQUIRED = 3;
    TARGET_STATE_LOST = 4;
    TARGET_STATE_NEUTRALIZED = 5;
}

message TargetResponse {
    string id = 1;
    Timestamp updated_date = 2;
    TrackingLocationDto tracking_location = 3;
    TargetState state = 4;
    string workspace_id = 5;
}

message TargetResponseList {
    repeated TargetResponse targets = 1;
}
