# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: target_proto.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'target_proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12target_proto.proto\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"\x92\x01\n\x13TrackingLocationDto\x12\x11\n\tlongitude\x18\x01 \x01(\x11\x12\x10\n\x08latitude\x18\x02 \x01(\x11\x12\x11\n\ttimestamp\x18\x03 \x01(\x07\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x11\x12\x17\n\x0fspeedOverGround\x18\x05 \x01(\r\x12\x18\n\x10\x63ourseOverGround\x18\x06 \x01(\r\"\xb2\x01\n\x15TrackingLocationDelta\x12\x16\n\x0elongitudeDelta\x18\x01 \x01(\x11\x12\x15\n\rlatitudeDelta\x18\x02 \x01(\x11\x12\x16\n\x0etimestampDelta\x18\x03 \x01(\x11\x12\x15\n\raltitudeDelta\x18\x04 \x01(\x11\x12\x1c\n\x14speedOverGroundDelta\x18\x05 \x01(\x11\x12\x1d\n\x15\x63ourseOverGroundDelta\x18\x06 \x01(\x11\"o\n\x19TrackingLocationDeltaList\x12*\n\x0c\x62\x61seLocation\x18\x01 \x01(\x0b\x32\x14.TrackingLocationDto\x12&\n\x06\x64\x65ltas\x18\x02 \x03(\x0b\x32\x16.TrackingLocationDelta\"\xa2\x01\n\x0eTargetResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12 \n\x0cupdated_date\x18\x02 \x01(\x0b\x32\n.Timestamp\x12/\n\x11tracking_location\x18\x03 \x01(\x0b\x32\x14.TrackingLocationDto\x12\x1b\n\x05state\x18\x04 \x01(\x0e\x32\x0c.TargetState\x12\x14\n\x0cworkspace_id\x18\x05 \x01(\t\"6\n\x12TargetResponseList\x12 \n\x07targets\x18\x01 \x03(\x0b\x32\x0f.TargetResponse*\xab\x01\n\x0bTargetState\x12\x18\n\x14TARGET_STATE_UNKNOWN\x10\x00\x12\x17\n\x13TARGET_STATE_ACTIVE\x10\x01\x12\x19\n\x15TARGET_STATE_INACTIVE\x10\x02\x12\x19\n\x15TARGET_STATE_ACQUIRED\x10\x03\x12\x15\n\x11TARGET_STATE_LOST\x10\x04\x12\x1c\n\x18TARGET_STATE_NEUTRALIZED\x10\x05\x42\x12\n\x10\x63om.somewear.genb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'target_proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.somewear.gen'
  _globals['_TARGETSTATE']._serialized_start=732
  _globals['_TARGETSTATE']._serialized_end=903
  _globals['_TIMESTAMP']._serialized_start=22
  _globals['_TIMESTAMP']._serialized_end=65
  _globals['_TRACKINGLOCATIONDTO']._serialized_start=68
  _globals['_TRACKINGLOCATIONDTO']._serialized_end=214
  _globals['_TRACKINGLOCATIONDELTA']._serialized_start=217
  _globals['_TRACKINGLOCATIONDELTA']._serialized_end=395
  _globals['_TRACKINGLOCATIONDELTALIST']._serialized_start=397
  _globals['_TRACKINGLOCATIONDELTALIST']._serialized_end=508
  _globals['_TARGETRESPONSE']._serialized_start=511
  _globals['_TARGETRESPONSE']._serialized_end=673
  _globals['_TARGETRESPONSELIST']._serialized_start=675
  _globals['_TARGETRESPONSELIST']._serialized_end=729
# @@protoc_insertion_point(module_scope)
