# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: target_proto.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'target_proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12target_proto.proto\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"L\n\x13TrackingLocationDto\x12\x11\n\tlongitude\x18\x01 \x01(\x11\x12\x10\n\x08latitude\x18\x02 \x01(\x11\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x11\"]\n\x15TrackingLocationDelta\x12\x16\n\x0elongitudeDelta\x18\x01 \x01(\x11\x12\x15\n\rlatitudeDelta\x18\x02 \x01(\x11\x12\x15\n\raltitudeDelta\x18\x04 \x01(\x11\"o\n\x19TrackingLocationDeltaList\x12*\n\x0c\x62\x61seLocation\x18\x01 \x01(\x0b\x32\x14.TrackingLocationDto\x12&\n\x06\x64\x65ltas\x18\x02 \x03(\x0b\x32\x16.TrackingLocationDelta\"\xa2\x01\n\x0eTargetResponse\x12\n\n\x02id\x18\x01 \x01(\r\x12 \n\x0cupdated_date\x18\x02 \x01(\x0b\x32\n.Timestamp\x12/\n\x11tracking_location\x18\x03 \x01(\x0b\x32\x14.TrackingLocationDto\x12\x1b\n\x05state\x18\x04 \x01(\x0e\x32\x0c.TargetState\x12\x14\n\x0cworkspace_id\x18\x05 \x01(\x04\"\xa5\x01\n\x13TargetResponseDelta\x12\x10\n\x08id_delta\x18\x01 \x01(\x11\x12 \n\x0cupdated_date\x18\x02 \x01(\x0b\x32\n.Timestamp\x12.\n\x0elocation_delta\x18\x03 \x01(\x0b\x32\x16.TrackingLocationDelta\x12 \n\x05state\x18\x04 \x01(\x0e\x32\x0c.TargetStateH\x00\x88\x01\x01\x42\x08\n\x06_state\"{\n\x17TargetResponseDeltaList\x12$\n\x0b\x62\x61se_target\x18\x01 \x01(\x0b\x32\x0f.TargetResponse\x12$\n\x06\x64\x65ltas\x18\x02 \x03(\x0b\x32\x14.TargetResponseDelta\x12\x14\n\x0cworkspace_id\x18\x03 \x01(\x04\"7\n\x0cTargetUpdate\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1b\n\x05state\x18\x04 \x01(\x0e\x32\x0c.TargetState*|\n\x0bTargetState\x12\x18\n\x14TARGET_STATE_UNKNOWN\x10\x00\x12\x1a\n\x16TARGET_STATE_CONFIRMED\x10\x01\x12\x1c\n\x18TARGET_STATE_NEUTRALIZED\x10\x02\x12\x19\n\x15TARGET_STATE_INACTIVE\x10\x03\x42\x12\n\x10\x63om.somewear.genb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'target_proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.somewear.gen'
  _globals['_TARGETSTATE']._serialized_start=868
  _globals['_TARGETSTATE']._serialized_end=992
  _globals['_TIMESTAMP']._serialized_start=22
  _globals['_TIMESTAMP']._serialized_end=65
  _globals['_TRACKINGLOCATIONDTO']._serialized_start=67
  _globals['_TRACKINGLOCATIONDTO']._serialized_end=143
  _globals['_TRACKINGLOCATIONDELTA']._serialized_start=145
  _globals['_TRACKINGLOCATIONDELTA']._serialized_end=238
  _globals['_TRACKINGLOCATIONDELTALIST']._serialized_start=240
  _globals['_TRACKINGLOCATIONDELTALIST']._serialized_end=351
  _globals['_TARGETRESPONSE']._serialized_start=354
  _globals['_TARGETRESPONSE']._serialized_end=516
  _globals['_TARGETRESPONSEDELTA']._serialized_start=519
  _globals['_TARGETRESPONSEDELTA']._serialized_end=684
  _globals['_TARGETRESPONSEDELTALIST']._serialized_start=686
  _globals['_TARGETRESPONSEDELTALIST']._serialized_end=809
  _globals['_TARGETUPDATE']._serialized_start=811
  _globals['_TARGETUPDATE']._serialized_end=866
# @@protoc_insertion_point(module_scope)
